### ISSUE TITLE
WebTransport support

### ISSUE THREAD

**Issue by bfelbo** [akshetpandey/react-native-cronet#37]
Hi, thank you for this library!

WebTransport seems to be supported by Cronet as the WebTransport APIs are available in Chromium/Chrome since version 97. I was wondering if you have considered adding WebTransport to this library?

It'd be huge to add WebTransport support to help RN devs develop real-time apps and games! WebTransport is now [supported by 76%+ of global devices](https://caniuse.com/webtransport) and [WebKit proclaimed their support of WebTransport](https://github.com/WebKit/standards-positions/issues/18#issuecomment-1495890122) so we might get Safari support this summer, which would make it supported across all major browsers. WebTransport is about to take off, and it'd be awesome to have support for it in RN!

**Comment by akshetpandey** [comment]
WT will be beyond the scope of this library. 

Cronet/and native networking stack already provides the raw tcp/udp channels required to build WT. Theoretically someone can make a WT shim for RN, but that won't have much to do with cronet. Also when 

It is of interest to browsers because they do not expose that to websites.
